import "./globals.css";


export const metadata = {
  title: "Binance - Cryptocurrency Exchange for Bitcoin, Ethereum & Altcoins",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link rel="icon" href="/img/logo-2.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
